# fly.toml app configuration file generated for java24on on 2025-04-01T11:15:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'java24on'
primary_region = 'ams'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
