name: Quarkus Build
on:
  push:
    branches:
      - main
env:
  QUARKUS_CONTAINER_IMAGE_PUSH: 'true'
  QUARKUS_CONTAINER_IMAGE_ADDITIONAL_TAGS: 'latest'
  QUARKUS_CONTAINER_IMAGE_USERNAME: '${{ vars.QUARKUS_CONTAINER_IMAGE_USERNAME }}'
  QUARKUS_CONTAINER_IMAGE_PASSWORD: '${{ secrets.QUARKUS_CONTAINER_IMAGE_PASSWORD }}'
jobs:
  build:
    name: quarkus build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'temurin'
          java-version: '24'
      - name: Cache m2 dependencies
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with maven
        id: mavenbuild
        run: |
          mvn -B -q package
